src/app/view/redButton..js

Testowe wgrywanie pliku Buttona

00 testowy plik

---

src/app/logic/correctAnswer.js

Create a function that verifies the correctness of the answer

---

src/app/view/components/createLogo.js
src/app/view/view.js

#60 Little fix for createLogo

---

src/app/utils/clearActive.js
src/app/view/components/mainMenu.js

#6 #6/UI/MainMenuOption Eslint changes

---

src/app/data/consts.js

-changed value of 'ids' property from string to number (which is use later as number)
-added static field DECIMAL_SYSTEM = 10, to some math formulas

Consts.js / actualization of content

---

src/app/data/consts.js
src/app/logic/dataManager.js
src/app/logic/mainQuestionManager.js
tests/questionTest.js

-added logic to getting answers to houses mode
-actualization of consts.js -added array of hogwart houses
-actualization og questionManager - changed to use GAME_MODES object
-actualization of questionTest to test also houses mode

#64/logic/actualization question generator

---

src/wand.js

Some improvements for future

---

index.html
package-lock.json
src/app/controller/controller.js
src/app/logic/correctAnswer.js
src/app/view/components/timerText.js
src/app/view/view.js
src/wand.js

Fixed developement errors

---

src/app/logic/player.js
tests/playerTest.js

#89/playercomeback

---

src/app/view/components/createImage.js
src/app/view/view.js
static/styles/index.scss

#92 Fixed git issues, added image, fixed logo

---

src/app/logic/gameMaker.js
src/app/logic/player.js

-to Player class added function checkAndRegisterAnswer, which makes missing work and contains old function registerAnswer, which is modified
-now registerAnswer is only adding data to detailQuestionData
- checkAndRegisterAnswer also add points to player result
GameMaker:
-removed checkAnswer function
-modified checkAndRegisterAnswer to changes in Player file
Tested in gameMakerTest.js - works again

Fixed bugs connected to removal correctAnswer file:

---

static/styles/_mainMenu.scss
static/styles/_vars.scss
static/styles/index.scss

button-height var added
header button before - fixed width

Fixed .header image-logo positioning, .game-image conflict resolved

---

src/app/view/components/displayTimerText.js
src/app/view/view.js
static/styles/_timerText.scss
static/styles/_wand.scss

displayTimerText function tested with logic but not connected yet

#36/UI/timer text

---

src/app/view/components/modeRules.js

- Changed general text and grammar of Mode Rules

#136/UI/ minor text changes

---

src/app/view/view.js
static/styles/_quitGame.scss

-Wand Cursor apears on Quit Button and Header
-Quit Game works by clicking on text "quit game" too -  not only by clicking on "quit icon"

#155/UI/ Fix cursor apearance on header and quit button

---

src/app/view/view.js

Settings button appear in the right place.

#166 Fix Settings Button

---

src/app/view/view.js
static/styles/_wand.scss
static/styles/index.scss

-Branch created to Fix #175 problem with naming Git branches with spaces

#179/UI/git naming fix btn styles

---

src/app/controller/controller.js
src/app/view/view.js

-added if statement to check level --> timers are removed only when they were created

#178/Fix-bug - removing timer vs easy mode

---

src/app/logic/timer.js

-changed if-else statement to make differences when time goes to endvs quit game

#185/bug-with-timer

---

src/app/view/view.js

-created wrapper-functions for removing classes and for removing attributes

#189/put-multiplied-code-in-one-function

---

package.json

Remove Klaudia, add Robert, change the name of Weronika.

---

src/app/data/consts.js
src/app/view/components/modal/modalForm.js
src/app/view/components/modal/modalWindow.js
static/styles/_modalStyles.scss

closes #39 
-table head alignment fixes

#139/1/modal window complete updated with new devvelopment

---

src/app/view/view.js

-added flag of settings when shown mode view, which covers settings view

#192/fix-settings-with-undefined-mode

---

src/app/view/components/modal/modalWindow.js

-added function for changing text depend on result

#218/text-in-modal
